// <auto-generated />
namespace BudgetApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newbuild : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newbuild));
        
        string IMigrationMetadata.Id
        {
            get { return "201604270444543_newbuild"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
